# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$all$fill$memory_usage$time$line_break\
$character\
"""

add_newline = false

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[time]
disabled = false
format = '[ $time]($style) '
style = 'white'

[fill]
symbol = ' '

[memory_usage]
disabled = false
threshold = 0
format = '$symbol[$ram]($style) '

[sudo]
disabled = false

[gcloud]
disabled = true
