"$schema" = "https://raw.githubusercontent.com/yazi-rs/schemas/main/schemas/theme.json"

[mgr]
border_symbol = " "

# from https://raw.githubusercontent.com/vampirelinux/css/master/ayu-mirage.tmTheme
syntect_theme = "~/dotfiles/yazi/ayu-mirage.tmTheme"

# Darkened background for selection
hovered = { bg = "#363A4F" }
preview_hovered = { underline = false }

[status]
# Progress
progress_label = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#6ccbfa", bg = "#45475a" }
progress_error = { fg = "#f38ba8", bg = "#45475a" }

# Permissions
perm_type = { fg = "#6ccbfa" }
perm_read = { fg = "#f9e2af" }
perm_write = { fg = "#f38ba8" }
perm_exec = { fg = "#a6e3a1" }
perm_sep = { fg = "#7f849c" }

[mode]
# Normal mode
normal_main = { fg = "#1e1e2e", bg = "#6ccbfa", bold = true }
normal_alt = { fg = "#6ccbfa", bg = "#363A4F" }

# Select mode
select_main = { fg = "#1e1e2e", bg = "#a6e3a1", bold = true }
select_alt = { fg = "#a6e3a1", bg = "#363A4F" }

# Unset mode
unset_main = { fg = "#1e1e2e", bg = "#f2cdcd", bold = true }
unset_alt = { fg = "#f2cdcd", bg = "#363A4F" }
